language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: FHaWV566lmUzEAXay1mj9q1EusMJdXGdgIMf+KaPw6sgp+fauzxJbucouwsEf66Q0TvAnabsGNrRF1SU44towwaQHIwaS2dUz3sUqUFKsiHlDTZHWyphBMPwplQNtTFxgCUXP6KcJcAJSQOzeYXLEEhIHmbtpn3YYdkepY1m1+7GBG3W8qbWX+R6ZdJMzKSHVc/pPLt3LuelbElJf5wNmqRFTNUhfwX7OLQZoaEKIPTejjPnQdhyfatXud7gFD1nYaOpQlk9hdtBst5xaQkYimr2OeoiiYgwrnppg3I/WrR71DeGt6SJS9WE4KvU5ttafZ7st8mWvMWcH/G7H4uj8yxrn5xeFXsWgDpvSkJZvR65pgP/pOGz+QKVW/WTDmEn4J+uVrF3YE31k7p/MQknZCjZrZpPeHcFi3FvqVY+aoqO2PrOYNYb7+oYHNw8KjNd3DkZILo6+WwkbgWd3GTg+uX0VzP4OZCkVv3V6vg++nu48FYWzBsBvbQBqB62AEBt/6c8W9hhpUnKJJ3X9/RUBveOxISmIrUJ18WTjY1zSFKdcaVoVkTb8YLI2OADDH93LFKI+Uq4zhifJq974sH4BImtWv4jpRJcFUA2oVZd8LcirQkGtFZLt3vrrGPdunsBtUtO4uLkzUFn/6rEjMJQQJcDHHkq8H+0+Zgch1tback=
  file: build/distributions/xld-aws-ecs-plugin-2.0.0.xldp
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xld-aws-ecs-plugin
